apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-desktop
  labels:
    app: ubuntu-desktop
spec:
  containers:
    - name: ubuntu-desktop
      image: ghcr.io/chipclee/ubuntu-desktop/gui:main-143c788-251222125603
      ports:
        - name: web
          containerPort: 6901
        - name: vnc
          containerPort: 5900
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-desktop
spec:
  selector:
    app: ubuntu-desktop
  type: NodePort
  ports:
    - name: web
      port: 6901
      targetPort: 6901
      nodePort: 30080
    - name: vnc
      port: 5900
      targetPort: 5900
      nodePort: 30900
